export const ACCESS_TOKEN =
  "eyAidHlwIjogIkpXVCIsICJhbGciOiAiRWREU0EiIH0.eyAiaXNzIjogInI6MEVGOF8yNDM2MjkzQ19CQjRFOSIsICJzdWIiOiAiNzY1NjExOTgxNjQ2NjA4MDkiLCAiYXVkIjogWyAid2ViOmNvbW11bml0eSIgXSwgImV4cCI6IDE3MjAxMjkyNDAsICJuYmYiOiAxNzExNDAyNDkzLCAiaWF0IjogMTcyMDA0MjQ5MywgImp0aSI6ICIwRjIxXzI0QTRFNzdFXzRCRkI1IiwgIm9hdCI6IDE3MTI2MjE2OTYsICJydF9leHAiOiAxNzMxMDMyODk0LCAicGVyIjogMCwgImlwX3N1YmplY3QiOiAiMTc4LjIwNS44NS4xNDgiLCAiaXBfY29uZmlybWVyIjogIjE3OC4yMDUuODUuMTQ4IiB9.-96Apn0Is8LCRb0IWIuvsqRPFZNcXrts-xA5Ns7cRHra9kIhDCkoyRnnE5bWD6Vli4NN5iUua3TGruOG7BFWBA"
export const BASE_URL = `https://market.csgo.com/api/v2/`
export const BASE_URL_USER = `https://market-old.csgo.com/`
export const BASE_URL_STEAMMARKET = `https://steamcommunity.com/market/listings/730/`
export const API_KEY = "99nP6l7m8tZY6K3qEj20qgr2FvwwTP1"
